paths:
  static: public
  uploads: public/uploads
timezone: Asia/Calcutta
markdown:
  engine: commonmark
  options:
    gfm: true
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
  source:
    path: ''
    icon: package_2
  work:
    path: src/content/work
    icon: work
